//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amirhanov_Exam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CleaningGroupMembers
    {
        public int MemberID { get; set; }
        public int GroupID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime AssignedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual CleaningGroups CleaningGroups { get; set; }
    }
}
