//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amirhanov_Exam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CleaningGroups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CleaningGroups()
        {
            this.CleaningGroupMembers = new HashSet<CleaningGroupMembers>();
        }
    
        public int GroupID { get; set; }
        public int OrderID { get; set; }
        public string GroupName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CleaningGroupMembers> CleaningGroupMembers { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
